[project]
name = "alx-backend-caching-property-listings"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=6.0.1",
    "django-redis>=6.0.0",
    "psycopg2-binary>=2.9.11",
]
